<?php

declare(strict_types=1);

use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer $this */

$this->headTitle('Home');
?>

<div class="jumbotron">
    <h1>Mezzio &amp; Keycloak OpenID Connect Example</h1>
    <p>
        This simple app serves as a bare-bones example of offloading user management and authentication to a Keycloak server.
    </p>
</div>

<div class="row">
    <div class="col">
        <h2>Introduction</h2>
        <p>
            The Mezzio app is a fresh install of the <a href="https://docs.mezzio.dev/mezzio/v3/getting-started/quick-start/">skeleton</a>
            with a handful of additional dependencies and some additional routes.
        </p>
        <p>
            First of all, providing you haven't logged in and registered yet, you'll receive a 403 error at
            '<a href="<?= $this->url('secret') ?>"><?= $this->url('secret') ?></a>'.
        </p>
        <p>
            The middleware pipeline for this route contains the default <code>Mezzio\Authentication\AuthenticationMiddleware</code>,
            followed by a request handler that renders some HTML content.
        </p>
        <p>
            The <a href="<?= $this->url('auth') ?>"><?= $this->url('auth') ?></a> route redirects you to the Keycloak
            server for registration and authentication, completes the
            <a href="https://fusionauth.io/articles/oauth/modern-guide-to-oauth#authorization-code-grant">Authorization Code Grant flow</a>
            and persists your access and refresh tokens in your session.
        </p>
        <p>
            Once you've been authenticated, you'll be able to access <a href="<?= $this->url('secret') ?>"><?= $this->url('secret') ?></a>
            and witness the wonders therein.
        </p>
        <p>
            Finally, the <a href="<?= $this->url('logout') ?>"><?= $this->url('logout') ?></a> route clears your local session,
            redirects you to the Keycloak logout endpoint which in turn redirects you back to this application.
        </p>
    </div>

    <div class="col">
        <h2>Key Documentation Sites</h2>
        <div class="list-group">
            <a class="list-group-item list-group-item-action" href="https://docs.mezzio.dev">Mezzio Docs</a>
            <a class="list-group-item list-group-item-action" href="https://www.keycloak.org/documentation">Keycloak Docs</a>
            <a class="list-group-item list-group-item-action" href="https://oauth2-client.thephpleague.com">League OAuth Client Docs</a>
            <a class="list-group-item list-group-item-action" href="https://docs.mezzio.dev/mezzio-authentication/">Mezzio Authentication</a>
        </div>
    </div>

</div>
