<?php

declare(strict_types=1);

use Laminas\View\Renderer\PhpRenderer;
use Lcobucci\JWT\Encoding\JoseEncoder;
use Lcobucci\JWT\Token\Parser;
use League\OAuth2\Client\Token\AccessToken;

/** @var PhpRenderer $this */

$this->headTitle('Secret Content');

$expires = $this->accessTokenExpiryDate ?? null;
assert($expires instanceof DateTimeImmutable);

$token = $this->token ?? null;
assert($token instanceof AccessToken);


$showToken = function (string $token, string $title): string {
    $parser = new Parser(new JoseEncoder());
    $parsed = $parser->parse($token);

    return <<<HTML
        <div class="card mb-4 shadow-sm">
            <div class="card-header">
                <h2>{$title}</h2>
            </div>
            <div class="card-body">
                <h3>JWT Headers</h3>
                <pre class='code'>{$this->escapeHtml(json_encode($parsed->headers()->all(), JSON_PRETTY_PRINT))}</pre>
                <h3>JWT Claims</h3>
                <pre class="code">{$this->escapeHtml(json_encode($parsed->claims()->all(), JSON_PRETTY_PRINT))}</pre>
            </div>
        </div>
        HTML;
};

?>

<div class="row pb-4">
    <div class="col">
        <h1>This content is top secret</h1>
        <p>Your access token will expire on <?= $expires->format('l jS F Y H:i:s e') ?></p>
        <h2>User information we have for you:</h2>
        <pre class="code"><?= $this->escapeHtml(json_encode($this->user, JSON_PRETTY_PRINT)) ?></pre>
        <h2>The tokens in your session:</h2>
        <pre class="code"><?= $this->escapeHtml(json_encode($token, JSON_PRETTY_PRINT)) ?></pre>
    </div>
</div>

<?= $showToken($token->getToken(), 'Access Token') ?>
<?= $showToken($token->getRefreshToken(), 'Refresh Token') ?>
<?= $showToken($token->getValues()['id_token'], 'ID Token') ?>
