<?php

declare(strict_types=1);

use Laminas\View\Renderer\PhpRenderer;

/** @var PhpRenderer $this */

$this->headLink()
    ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css')
    ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.6.2/css/bootstrap.min.css');
$this->inlineScript()
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/jquery/3.7.1/jquery.min.js')
    ->appendFile('https://cdnjs.cloudflare.com/ajax/libs/bootstrap/4.6.2/js/bootstrap.min.js');
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <link rel="shortcut icon" href="https://getlaminas.org/images/favicon/favicon.ico" />
    <?=$this->headTitle('mezzio')->setSeparator(' - ')->setAutoEscape(false)?>
    <?=$this->headMeta()?>
    <?=$this->headLink()?>
    <style>
        body { padding-top: 70px; }
        .app { min-height: 100vh; }
        .app-footer { padding-bottom: 1em; }
        .mezzio-green, h2 a, h2 a:hover { color: #009655; }
        .navbar-brand { padding: 0; }
        .navbar-brand img { margin: -.5rem 0; filter: brightness(0) invert(1); }
    </style>
</head>
<body class="app">
    <header class="app-header">
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="#navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <!-- Brand -->
                    <a class="navbar-brand" href="<?=$this->url('home')?>">
                        <img src="https://docs.laminas.dev/img/laminas-mezzio-rgb.svg" alt="Laminas Mezzio" height="56" />
                    </a>
                </div>
                <!-- Links -->
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class='nav-item'>
                            <a href="<?= $this->url('auth') ?>" class='nav-link'>
                                <i class="fa fa-lock"></i>
                                Authenticate
                            </a>
                        </li>
                        <li class='nav-item'>
                            <a href="<?= $this->url('secret') ?>" class='nav-link'>
                                <i class='fa fa-user-secret'></i>
                                Secret Content
                            </a>
                        </li>
                        <li class='nav-item'>
                            <a href="<?= sprintf('https://%s/admin/', getenv('KC_HOSTNAME')) ?>" class='nav-link'>
                                <i class='fa fa-cogs'></i>
                                Keycloak Admin
                            </a>
                        </li>
                        <li class="nav-item">
                            <a href="https://github.com/gsteel/mezzio-keycloak" class="nav-link">
                                <i class="fab fa-github"></i>
                                Contribute
                            </a>
                        </li>
                        <li class='nav-item'>
                            <a href='<?= $this->url('logout') ?>' class='nav-link'>
                                <i class='fas fa-power-off'></i>
                                Logout
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="app-content">
        <main class="container">
            <?=$this->content?>
        </main>
    </div>

    <footer class="app-footer">
        <div class="container">
            <hr />
            <p>
                &copy; <?=date('Y')?> <a href="https://getlaminas.org/">Laminas Project</a> a Series of LF Projects, LLC.
            </p>
        </div>
    </footer>

    <?=$this->inlineScript()?>
</body>
</html>
