name: "Continuous Integration"

on:
  pull_request:
  push:
    branches:
      - '[0-9]+.[0-9]+.x'
      - 'renovate/**'
    tags:

env:
  php_extensions: ctype, curl, intl, json, mbstring, pcre, redis, sockets, opcache
  default_php: 8.2

jobs:

  cs-check:
    name: CS Checks
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.default_php }}
          extensions: ${{ env.php_extensions }}
          tools: cs2pr

      - uses: "ramsey/composer-install@2.2.0"

      - name: "Check CS"
        run: vendor/bin/phpcs --report=checkstyle -q | cs2pr

  psalm:
    name: Psalm Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3

      - name: "Setup PHP"
        if: hashFiles('psalm.xml') != ''
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.default_php }}
          extensions: ${{ env.php_extensions }}
          tools: cs2pr

      - uses: "ramsey/composer-install@2.2.0"
        if: hashFiles('psalm.xml') != ''

      - name: "Psalm"
        if: hashFiles('psalm.xml') != ''
        run: vendor/bin/psalm --output-format=github

  run-tests:

    name: PHPUnit on ${{ matrix.php-version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        php-version: ['8.2']

    steps:
      - name: "Checkout Code"
        uses: actions/checkout@v3

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ${{ env.php_extensions }}
          coverage: pcov
          ini-values: pcov.enabled=1

      - uses: "ramsey/composer-install@2.2.0"
        with:
          composer-options: "${{ matrix.composer-options }}"

      - name: "Run Tests"
        run: php ./vendor/bin/phpunit

  composer-require-checker:
    name: "Check for missing dependencies"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ env.default_php }}
          ini-values: memory_limit=-1
          extensions: ${{ env.php_extensions }}

      - uses: "ramsey/composer-install@2.2.0"

      - name: "Set global composer bin-dir"
        run: composer global config bin-dir /usr/local/bin

      - name: "Install require checker"
        run: composer global require -W maglnet/composer-require-checker

      - name: "Check"
        run: /usr/local/bin/composer-require-checker check
